###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
        "name": "Jose Familia",
        "age": 20,
        "email": "josefamilia@email.com"
}

###
GET http://localhost:3000/api/users HTTP/1.1

###
GET http://localhost:3000/api/users/65774bed2fd53fae8ad5ff8a HTTP/1.1

###
DELETE http://localhost:3000/api/users/65774bed2fd53fae8ad5ff8a HTTP/1.1

###
PUT http://localhost:3000/api/users/65774bed2fd53fae8ad5ff8a HTTP/1.1
Content-Type: application/json

{
        "name": "Jose Familia",
        "age": 20,
        "email": "josefamilia@email.com"
}